table:
  size: [0.80, 0.70, 0.40]
  top_z: 0.4
arm: [0.0, 0.0]
grids:
  P1: [0.141018, 0.072702]
  P2: [0.08037, -0.12506]
  P3: [-0.08037, 0.12506]
  P4: [-0.13213, -0.06812]
bins:
  BIN_A: [0.135229, -0.036238]
  BIN_B: [-0.11782, 0.05494]
objects:
  orange_battery:
    model: orange_battery_1
    grid: P1
    bin: BIN_A
  green_can:
    model: green_can_1
    grid: P4
    bin: BIN_B
camera:
  topic: /task3/camera/image_raw
  pose: [0.0, 0.0, 1.35, 0.0, 1.5708, 0.0]
  image_size: [640, 480]
  update_rate: 30
  horizontal_fov: 1.05
