<?xml version="1.0"?>
<package format="3">
  <name>task3_interfaces</name>
  <version>0.1.0</version>
  <description>Task3 action interface for one-object physical sorting.</description>
  <maintainer email="team@example.com">Integrated Robot Program Group Team</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>rosidl_default_generators</buildtool_depend>
  <depend>action_msgs</depend>
  <depend>rosidl_default_runtime</depend>

  <member_of_group>rosidl_interface_packages</member_of_group>
</package>
